apiVersion: v1
kind: Service
metadata:
  name: {{ include "datasette.fullname" . }}
  labels:
    {{- include "datasette.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    {{- include "datasette.selectorLabels" . | nindent 4 }}
