{{- $fullName := include "api.fullname" . -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: {{ .Values.ingress.rule }}
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: 80