{{- if .Values.ingressroute.enabled -}}
{{- $fullName := include "website.fullname" . -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: {{ .Values.ingressroute.rule }}
      services:
        - name: {{ $fullName }}
          port: 80
      # middlewares:
      #   - name: website-default-redirect
      #     namespace: sledilnik-prod
  tls:
    certResolver: {{ .Values.ingressroute.tls.certResolver }}
    {{- if .Values.ingressroute.tls.main }}
    main: {{ .Values.ingressroute.tls.main }}
    {{- end }}
    {{- with .Values.ingressroute.tls.sans }}
    sans:
      {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}