{{- $fullName := include "website.fullname" . -}}
{{- $rule := include "website.ingressrule" . -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: {{ $rule }}
      services:
        - name: {{ $fullName }}
          port: 80
  tls:
    certResolver: letsencrypt