apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "django.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        {{- include "django.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: django-collectstatic
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["./manage.py", "collectstatic"]
        envFrom:
          - configMapRef:
              name: {{.Release.Name}}-config
        volumeMounts:
          - name: static
            mountPath: {{ .Values.static.path }}