{{- if .Values.migrateJob.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "django.fullname" . }}-migrate
  labels:
    {{- include "django.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: django-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["python3", "manage.py", "migrate", "--noinput"]
        envFrom:
          {{- if .Values.configmap.enabled }}
          - configMapRef:
              name: {{ .Release.Name }}-config
          {{- end}}
          - secretRef:
              name: {{ .Values.existingSecret }}
        volumeMounts:
          - name: data
            mountPath: {{ .Values.persistence.mediaPath }}
            subPath: media
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-sqlite" (include "django.fullname" .)) }}
{{- end }}