apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "django.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        {{- include "django.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: django-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["python3", "manage.py", "migrate"]
        envFrom:
          - configMapRef:
              name: {{.Release.Name}}-config
        volumeMounts:
          - name: sqlite
            mountPath: {{ .Values.sqlite.path }}/{{ .Values.sqlite.dbName }}
            subPath: {{ .Values.sqlite.dbName }}
      volumes:
        - name: sqlite
          persistentVolumeClaim:
            claimName: {{ .Values.sqlite.existingClaim | default (printf "%s-sqlite" (include "django.fullname" .)) }}