apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy-ctrl.fullname" . }}
  labels:
    {{- include "deploy-ctrl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "deploy-ctrl.selectorLabels" . | nindent 4 }}
